collections_dir = 'data/collections'

[[collections]]

  id     = 'codes-rk'
  name   = 'Код РК'
  server = 'selt.ruskom'

  getter = 'ddl'
  object_types = [
    'PROCEDURE',
    'FUNCTION',
    'VIEW'
  ]


[[collections]]

  id     = 'codes-zra'
  name   = 'Код ЗРА'
  server = 'selt'

#[[collections]]
#
#  dir   = 'tables-rk'
#  slug  = 'tables-rk'
#  name  = 'Таблицы РК'
#
#[[collections]]
#
#  dir   = 'tables-zra'
#  slug  = 'tables-zra'
#  name  = 'Таблицы ЗРА'
